version: '3'
services:
  api:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      # 3000 for UI app (docker)
      # 8080 for UI app (webpack dev)
      CORS_ALLOW_ORIGINS: http://localhost:3000,http://localhost:8080
      PORT: 5000
      DATABASE_URL: postgres://kcoin:@db:5432/kcoin
  db:
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: kcoin
    image: postgres:9.6-alpine